services:
  prometheus:
    image: prom/prometheus
    container_name: middleware_prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    ports:
      - 9090:9090
    user: "1000:1000"
    command:
      - '--storage.tsdb.path=/prometheus'
#      - '--storage.tsdb.retention.time=60s'
      - '--config.file=/etc/prometheus/prometheus-config.yml'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    user: "1000:1000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    depends_on:
      - prometheus
