auth_enabled: false

server:
  http_listen_port: ${LOKI_HTTP_PORT}
  grpc_listen_port: ${LOKI_GRPC_PORT}
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0

ingester:
  wal:
    enabled: true
    dir: /var/lib/loki/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /var/lib/loki/index
    cache_location: /var/lib/loki/cache
  filesystem:
    directory: /var/lib/loki/chunks

limits_config:
  ingestion_rate_mb: 10
  ingestion_rate_strategy: "reject_oldest"
  reject_old_samples: false
  reject_old_samples_max_age: 168h

chunk_store_config: {}

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h
  
compactor:
  working_directory: /var/lib/loki/compactor
  