{
 "title": "Log_Analysis",
 "description": "Edge & Middleware logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "camera",
    "label": "Camera",
    "query": {}
   },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Middleware의 전체 Tibero 2K 로그 수",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"middleware-logs\", dbms_name=\"Tibero\", table_name=\"soitgrtmdtinfo_2K\"} [$__range]))"
      }
     ]
    },
    {
     "title": "전체 Edge 2K 성공 로그 수",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"edge-grpc-logs\", function=\"process_Soitgrtmdtinfo_2K_Request\"} |= \"data send success\" [$__range]))"
      }
     ]
    },
    {
     "title": "Middleware vs Edge",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$Middleware_Tibero - $Edge", "type": "math" },
      {
       "expression": "$Middleware_Tibero /  $Edge * 100",
       "type": "math"
      }
     ]
    }
   ]
  },
  { "title": "by Camera", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  { "title": "Camera Id", "type": "text", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 }, "options": { "content": "$camera" } },
  {
   "title": "Tibero 2K 로그 수",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"middleware-logs\", spot_camr_id=\"$camera\", dbms_name=\"Tibero\", table_name=\"soitgrtmdtinfo_2K\"} [$__range])) by (spot_camr_id)"
    }
   ]
  },
  {
   "title": "Edge 2K 성공 로그 수",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"edge-grpc-logs\", spot_camr_id=\"$camera\", function=\"process_Soitgrtmdtinfo_2K_Request\"} |= \"data send success\" [$__range])) by (spot_camr_id)"
    }
   ]
  },
  {
   "title": "Middleware vs Edge",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$Middleware_Tibero - $Edge", "type": "math" },
    {
     "expression": "$Middleware_Tibero /  $Edge * 100",
     "type": "math"
    }
   ]
  },
  { "title": "Middleware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Tibero 2K 로그 속도",
   "type": "timeseries",
   "description": "soitgrtmdtinfo_2K",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate({job=\"middleware-logs\", dbms_name=\"Tibero\", table_name=\"soitgrtmdtinfo_2K\"} [$__interval])) by (spot_camr_id)"
    }
   ]
  },
  {
   "title": "Tibero 2K 로그 발생 수",
   "type": "bargauge",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"middleware-logs\", dbms_name=\"Tibero\", table_name=\"soitgrtmdtinfo_2K\"} [$__range])) by (spot_camr_id)"
    }
   ]
  },
  { "title": "Edge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "2K 성공 로그 발생 속도",
   "type": "timeseries",
   "description": "초당 발생량",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({job=\"edge-grpc-logs\", function=\"process_Soitgrtmdtinfo_2K_Request\"} |= \"data send success\" [$__interval])) by (spot_camr_id)"
    }
   ]
  },
  {
   "title": "2K 성공 로그 수",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"edge-grpc-logs\", function=\"process_Soitgrtmdtinfo_2K_Request\"} |= \"data send success\" [$__range])) by (spot_camr_id)"
    }
   ]
  }
 ]
}